{{- if and (.Values.opensearch.in_cluster) (not .Values.opensearch.single_node) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-client
  labels: {{ include "logging.labels" . | indent 4 }}
    node: os
spec:
  replicas: {{ .Values.client.replicas }}
  selector:
    matchLabels: {{ include "logging.selectorLabels" . | indent 6 }}
      type: client
      node: os
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/opensearch/os-configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/opensearch/os-certificates-sec.yaml") . | sha256sum }}
      labels: {{ include "logging.selectorLabels" . | indent 8 }}
        type: client
        node: os
    spec:
      priorityClassName: {{ default .Values.priority_class .Values.client.priority_class }}
      {{- with .Values.client.affinity }}     
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.client.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Release.Name }}-priv
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}      
      {{- end }}
      {{- with .Values.client.topologySpreadConstraints }}
      topologySpreadConstraints: {{- toYaml . | nindent 8 }} 
      {{- end }}
      containers:
      - name: main
        image: {{ .Values.opendistro.image }}:{{ .Values.opendistro.imageTag }}        
        resources: {{ toYaml .Values.client.resources | nindent 10 }}
        livenessProbe:
          tcpSocket:
            port: transport
          initialDelaySeconds: 60
          periodSeconds: 60
        ports:
        - containerPort: 9300
          name: transport
        - containerPort: 9200
          name: http
        volumeMounts:
        - name: opensearch
          mountPath: /livenessProbe.sh
          subPath: livenessProbe.sh   
        - name: opensearch
          mountPath: /usr/share/opensearch/config/opensearch.yml
          subPath: opensearch.yml
        - name: opensearch
          mountPath: /usr/share/opensearch/config/log4j2.properties
          subPath: log4j2.properties
        - name: os-data
          mountPath: /data
        - name: certificates
          mountPath: /usr/share/opensearch/config/node.pem
          subPath: node.pem
        - name: certificates
          mountPath: /usr/share/opensearch/config/node-key.pem
          subPath: node-key.pem
        - name: certificates
          mountPath: /usr/share/opensearch/config/root-ca.pem
          subPath: root-ca.pem
        - name: certificates
          mountPath: /usr/share/opensearch/config/efk-rest.pem
          subPath: efk-rest.pem
        - name: certificates
          mountPath: /usr/share/opensearch/config/efk-rest-key.pem
          subPath: efk-rest-key.pem
        - name: certificates
          mountPath: /usr/share/opensearch/config/opensearch.truststore
          subPath: opensearch.truststore
        - name: certificates
          mountPath: /usr/share/opensearch/config/http.truststore
          subPath: http.truststore         
        {{- if .Values.opensearch.snapshot.enabled }}
        - name: os-snapshot
          mountPath: /snapshot
        {{- end }}          
        env:
        - name: os_url
          value: https://localhost:9200
        - name: os_user
          value: {{ .Values.opensearch.user }}
        - name: os_pass
          value: {{ .Values.opensearch.password }}  
        - name: OPENSEARCH_JAVA_OPTS
          value: "-Xms{{ .Values.client.heap_size }} -Xmx{{ .Values.client.heap_size }} \
                  {{ .Values.opensearch.additional_jvm_params }} \
                  -Djava.util.logging.config.file=/usr/share/opensearch/config/logging.properties"
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_MASTER
          value: "false"
        - name: NODE_DATA
          value: "false"
        - name: NODE_INGEST
          value: "false"        
      # opensearch requires vm.max_map_count to be at least 262144.
      # If your OS already sets up this number to a higher value, feel free
      # to remove this init container.
      initContainers:
      - image: {{ include "init_container.image" . }}
        imagePullPolicy: {{ .Values.init_container.imagePullPolicy }}
        command: ["sh", "-c", "/init/check_host_port.sh $es_master 9300 \
                   && /sbin/sysctl -w vm.max_map_count=262144 || true && chown 1000:1000  /data \
                   && if [ -d /snapshot ]; then chown 1000:1000 /snapshot ; fi"]
        name: init
        env:
          - name: es_master
            value: {{ .Release.Name }}-master-{{ (sub (.Values.master.replicas | int) 1) }}
        volumeMounts:
        - name: os-data
          mountPath: /data
        {{- if .Values.opensearch.snapshot.enabled }}
        - name: os-snapshot
          mountPath: /snapshot
        {{- end }} 
        - mountPath: "/init"          
          name: init          
        securityContext:
          runAsUser: 0
          privileged: true  
      volumes:
      - name: opensearch
        configMap:
          name: {{ .Release.Name }}
          defaultMode: 0755
      - name: init
        configMap:
          name: {{ .Release.Name}}-init
          defaultMode: 0755    
      {{- if .Values.opensearch.snapshot.enabled }}
      - name: os-snapshot
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-snapshot-pvc
      {{- end }}          
      - name: os-data
        emptyDir: {}
      - name: certificates
        secret:
          secretName: {{ .Release.Name }}-certificates
      - name: securityconfig
        secret:
          secretName: {{ .Release.Name }}-securityconfig    
{{- end }}
