{{- if .Values.opensearch.in_cluster }}
{{ range $dataId := until (.Values.data.replicas | int) }}    
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-data-{{ $dataId }}
  labels: {{ include "logging.labels" $ | indent 4 }}
spec:
  ports:
    - port: 9300
      name: transport    
    {{- if $.Values.opensearch.single_node }}
    - port: 9200
      name: http
    {{- end }}  
  selector: {{ include "logging.selectorLabels" $ | indent 4 }}
    {{- if $.Values.opensearch.single_node }}
    type: single
    {{- else }}
    statefulset.kubernetes.io/pod-name: {{ $.Release.Name }}-data-{{ $dataId }}    
    type: data
    {{- end }}
{{- end }}
{{- end }}