{{- if and (.Values.opensearch.in_cluster) (not .Values.opensearch.single_node) }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name:  {{ .Release.Name }}-master
  labels: {{ include "logging.labels" . | indent 4 }}
    node: os
spec:
  updateStrategy:
    type: RollingUpdate
  serviceName: {{ .Release.Name }}-master
  replicas: {{ .Values.master.replicas }}
  selector:
    matchLabels: {{ include "logging.selectorLabels" . | indent 6 }}
      type: master
      node: os
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/opensearch/os-configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/opensearch/os-certificates-sec.yaml") . | sha256sum }}
      labels: {{ include "logging.selectorLabels" . | indent 8 }}
        type: master
        node: os
    spec:
      priorityClassName: {{ default .Values.priority_class .Values.master.priority_class }}
      {{- with .Values.master.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.master.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Release.Name }}-priv
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml . | nindent 6 }}
      {{- end }}
      containers:
      - name: main
        image: {{ .Values.opendistro.image }}:{{ .Values.opendistro.imageTag }}
        resources: {{ toYaml .Values.master.resources | nindent 10 }}
        livenessProbe:
          tcpSocket:
            port: transport
          initialDelaySeconds: 60
          periodSeconds: 60
        ports:
        - containerPort: 9300
          name: transport
        volumeMounts:
        - name: os-data
          mountPath: /data
        {{- if .Values.opensearch.snapshot.enabled }}
        - name: os-snapshot
          mountPath: /snapshot
        {{- end }}          
        - name: opensearch
          mountPath: /usr/share/opensearch/config/opensearch.yml
          subPath: opensearch.yml
        - name: opensearch
          mountPath: /usr/share/opensearch/config/log4j2.properties
          subPath: log4j2.properties  
        - name: certificates
          mountPath: /usr/share/opensearch/config/node.pem
          subPath: node.pem
        - name: certificates
          mountPath: /usr/share/opensearch/config/node-key.pem
          subPath: node-key.pem
        - name: certificates
          mountPath: /usr/share/opensearch/config/root-ca.pem
          subPath: root-ca.pem
        - name: certificates
          mountPath: /usr/share/opensearch/config/efk-rest.pem
          subPath: efk-rest.pem
        - name: certificates
          mountPath: /usr/share/opensearch/config/efk-rest-key.pem
          subPath: efk-rest-key.pem
        - name: certificates
          mountPath: /usr/share/opensearch/config/opensearch.truststore
          subPath: opensearch.truststore  
        - name: certificates
          mountPath: /usr/share/opensearch/config/http.truststore
          subPath: http.truststore  
        - name: certificates
          mountPath: /usr/share/opensearch/config/keystore.jks
          subPath: keystore.jks        
        env:
        - name: "NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: OPENSEARCH_JAVA_OPTS
          value: "-Xms{{ .Values.master.heap_size }} -Xmx{{ .Values.master.heap_size }} {{ .Values.opensearch.additional_jvm_params }}"
        - name: NODE_DATA
          value: "false"
        - name: NODE_INGEST
          value: "false"
        - name: NODE_MASTER
          value: "true"
      volumes:
      - name: opensearch
        configMap:
          name: {{ .Release.Name }}
      {{- if .Values.opensearch.snapshot.enabled }}
      - name: os-snapshot
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-snapshot-pvc
      {{- end }}    
      - name: certificates
        secret:
          secretName: {{ .Release.Name }}-certificates
      - name: securityconfig
        secret:
          secretName: {{ .Release.Name }}-securityconfig    
      # opensearch requires vm.max_map_count to be at least 262144.
      # If your OS already sets up this number to a higher value, feel free
      # to remove this init container.
      initContainers:
      - name: init
        image: {{ include "init_container.image" . }}
        imagePullPolicy: {{ .Values.init_container.imagePullPolicy }}
        command: ["sh","-c","/sbin/sysctl -w vm.max_map_count=262144 || true && chown 1000:1000 /data && if [ -d /snapshot ]; then chown 1000:1000 /snapshot ; fi"]
        volumeMounts:
        - name: os-data
          mountPath: /data
        {{- if .Values.opensearch.snapshot.enabled }}
        - name: os-snapshot
          mountPath: /snapshot
        {{- end }}          
        securityContext:
          privileged: true  
          runAsUser: 0
  volumeClaimTemplates:
  - metadata:
      name: os-data
    spec:
      storageClassName: {{ default .Values.storage_class .Values.master.storage_class | quote }}
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.master.storage }}
{{- end }}
