{{- if .Values.opensearch.in_cluster }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-securityadmin
  labels: {{ include "logging.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  backoffLimit: 10
  template:
    metadata:
      annotations:
        "sidecar.istio.io/inject": "false"
    spec:
      restartPolicy: OnFailure 
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml . | nindent 6 }}
      {{- end }}
      initContainers:
      - name: init
        image: {{ include "init_container.image" . }}
        imagePullPolicy: {{ .Values.init_container.imagePullPolicy }}
        command: ["sh", "-c", "/init/check_host_port.sh $os_master 9300"]
        env:
          - name: os_master
            value: {{ .Release.Name }}-master-{{ (sub (.Values.master.replicas | int) 1) }}          
        volumeMounts:
        - mountPath: "/init"
          name: init
      containers:
      - name: main
        image: {{ .Values.opendistro.image }}:{{ .Values.opendistro.imageTag }}
        command: ["sh", "-c", "/setup.sh"]
        env:
          - name: os_url
            value: {{ include "os_url" . }}
          - name: os_node
            value: {{ .Release.Name }}-master-{{ (sub (.Values.master.replicas | int) 1) }}
          - name: os_user
            value: {{ .Values.opensearch.user }}
          - name: os_pass
            value: {{ .Values.opensearch.password }}
          - name: ki_user
            value: {{ .Values.opensearch_dashboards.user }}
          - name: ki_pass
            value: {{ .Values.opensearch_dashboards.password }}   
          - name: ki_ro_user
            value: {{ .Values.opensearch_dashboards.readonly.user }}
          - name: ki_ro_pass
            value: {{ .Values.opensearch_dashboards.readonly.password }}
          - name: ki_dev_user
            value: {{ .Values.opensearch_dashboards.developer.user }}
          - name: ki_dev_pass
            value: {{ .Values.opensearch_dashboards.developer.password }}       
        volumeMounts:
        - name: setup
          mountPath: /setup.sh
          subPath: setup.sh
        - name: certificates
          mountPath: /usr/share/opensearch/config/node.pem
          subPath: node.pem  
        - name: certificates
          mountPath: /usr/share/opensearch/config/node-key.pem
          subPath: node-key.pem
        - name: certificates
          mountPath: /usr/share/opensearch/config/root-ca.pem
          subPath: root-ca.pem
        - name: certificates
          mountPath: /usr/share/opensearch/config/admin.pem
          subPath: admin.pem  
        - name: certificates
          mountPath: /usr/share/opensearch/config/admin-key.pem
          subPath: admin-key.pem
        - name: securityconfig
          mountPath: /usr/share/opensearch/plugins/opensearch-security/securityconfig  
        - name: certificates
          mountPath: /usr/share/opensearch/config/http.truststore
          subPath: http.truststore  
      volumes:
      - name: certificates
        secret:
          secretName: {{ .Release.Name }}-certificates
      - name: securityconfig
        secret:
          secretName: {{ .Release.Name }}-securityconfig
          defaultMode: 0755
      - name: init
        configMap:
          name: {{ .Release.Name}}-init
          defaultMode: 0755
      - name: setup
        configMap:
          name: {{ .Release.Name}}-securityadmin
          defaultMode: 0755             
{{- end }}          
