_meta:
  type: "config"
  config_version: 2

config:
  dynamic:
    # Set filtered_alias_mode to 'disallow' to forbid more than 2 filtered aliases per index
    # Set filtered_alias_mode to 'warn' to allow more than 2 filtered aliases per index but warns about it (default)
    # Set filtered_alias_mode to 'nowarn' to allow more than 2 filtered aliases per index silently
    filtered_alias_mode: warn
    do_not_fail_on_forbidden: true
    kibana:
      multitenancy_enabled: true
      server_username: {{ .Values.opensearch_dashboards.user }}
      #index: '.opensearch-dashboards'
    http:
      anonymous_auth_enabled: false
      xff:
        enabled: false
        internalProxies: '192\.168\.0\.10|192\.168\.0\.11' # regex pattern
        #internalProxies: '.*' # trust all internal proxies, regex pattern
        #remoteIpHeader:  'x-forwarded-for'
        ###### see https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html for regex help
        ###### more information about XFF https://en.wikipedia.org/wiki/X-Forwarded-For
        ###### and here https://tools.ietf.org/html/rfc7239
        ###### and https://tomcat.apache.org/tomcat-8.0-doc/config/valve.html#Remote_IP_Valve
    authc:
      basic_internal_auth_domain:
        description: "Authenticate via HTTP Basic against internal users database"
        http_enabled: true
        transport_enabled: true
        order: 0
        http_authenticator:
          type: basic
          challenge: true
        authentication_backend:
          type: intern
{{- if .Values.opendistro.saml.enabled }}                  
      saml_auth_domain:
        http_enabled: true
        transport_enabled: false
        order: 1
        http_authenticator:
          type: saml
          challenge: true 
          config:
            idp:
              enable_ssl: true      
              metadata_url: {{ .Values.opendistro.saml.idp.metadata_url }}
              entity_id: {{ .Values.opendistro.saml.idp.entity_id }}
            sp:
              entity_id: {{ .Values.opendistro.saml.sp.entity_id }} 
            opensearch-dashboards_url: https://{{ .Values.opensearch_dashboards.ingress.host }}
            roles_key: groups 
            exchange_key: {{ .Values.opendistro.saml.exchange_key }}
        authentication_backend:
          type: noop   
{{- end }}
