---
# In this file users, backendroles and hosts can be mapped to Open Distro Security roles.
# Permissions for Opendistro roles are configured in roles.yml

_meta:
  type: "rolesmapping"
  config_version: 2

# Define your roles mapping here

all_access:
  reserved: false
  backend_roles:
    - "administrator"
  description: "Maps external es user to admin role"

admin:
  reserved: false
  backend_roles:
    - "administrator"
  description: "Maps external es user to admin role"


opensearch-dashboards_admin:
  reserved: false
  users:
  - {{ .Values.opensearch_dashboards.user }} 
  description: "Maps external es user to admin role"


opensearch-dashboards_viewer:
  reserved: false
  backend_roles:
    - "Viewer"
  description: "Maps viewer backend role"

opensearch-dashboards_developer:
  reserved: false
  users:
    - {{ .Values.opensearch_dashboards.user }}
    - {{ .Values.opensearch_dashboards.developer.user }}
  and_backend_roles:
    - "Developer"
  description: "Maps developer backend role"  

opensearch-dashboards_user:
  reserved: false
  backend_roles:
    - "Viewer"
    - "Developer"
  description: "Maps viewer and developer backend roles to opensearch-dashboards_user role"  


kibana_user:
  reserved: false
  backend_roles:
    - "Developer"
  description: "Maps developer backend roles to kibana_user role"      